apiVersion: v1
kind: Pod
metadata:
  name: nginx-pv-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: ???
          name: ???
  volumes:
    - name: ???
      persistentVolumeClaim:
        claimName: ???